### ISSUE TITLE
Module not compatible with next generation lamassu-server

### ISSUE THREAD

**Issue by CrypticaScriptura** [seigneur/lamassu-itbit#2]
Module loads in lamassu-server@1.0.2 without errors.

When configuring on lamassu-server@2.2.5, lamassu-server.log throws errors:

```
[2015-05-15T15:20:34.357Z]  INFO: lamassu-server/349 on lamassu-liber: Version: 2.2.5
connect.multipart() will be removed in connect 3.0
visit https://github.com/senchalabs/connect/wiki/Connect-3.0 for alternatives
connect.limit() will be removed in connect 3.0
lamassu-server listening on port 3000 (https)

/usr/local/lib/node_modules/lamassu-server/lib/plugins.js:434
  tickerPlugin.ticker(deviceCurrency, function(err, resRates) {
               ^
TypeError: Cannot call method 'ticker' of null
    at pollRate (/usr/local/lib/node_modules/lamassu-server/lib/plugins.js:434:16)
    at onTickerChange (/usr/local/lib/node_modules/lamassu-server/lib/plugins.js:148:7)
    at loadOrConfigPlugin (/usr/local/lib/node_modules/lamassu-server/lib/plugins.js:128:5)
    at Object.configure (/usr/local/lib/node_modules/lamassu-server/lib/plugins.js:142:3)
    at /usr/local/lib/node_modules/lamassu-server/lib/app.js:32:13
    at /usr/local/lib/node_modules/lamassu-server/node_modules/lamassu-config/lib/main.js:96:5
    at null.callback (/usr/local/lib/node_modules/lamassu-server/node_modules/lamassu-config/lib/main.js:54:5)
    at Query.handleReadyForQuery (/usr/local/lib/node_modules/lamassu-server/node_modules/pg/lib/query.js:84:10)
    at null.<anonymous> (/usr/local/lib/node_modules/lamassu-server/node_modules/pg/lib/client.js:159:19)
    at emit (events.js:117:20)
```

Process used to configure: https://gist.github.com/naconner/dc097130bdbddf6b7d5e

Please note lamassu-server 2.x is not backwards compatible with lamassu-machine versions below 0.4.9. Both contain database changes to accomodate for two-way mode and dropped transaction support. 

Installation of next-gen server: https://github.com/lamassu/lamassu-install/tree/two-way

If you'd be interested in updating for compatibility with the latest versions, I'd be glad to provide more details. I know of another operator interested in using it, and we could include it as a dependency in lamassu-server.

**Comment by seigneur** [comment]
@naconner  Sounds good, I was aware of this, I am interested in updating it, although I hope the other operator is not time bound. I had not done it with the next version back then, because I think dev was still going on in some parts for the lamassu. Could you provide the additional details.

**Comment by CrypticaScriptura** [comment]
Great, @seigneur. You may use the install script linked above to create a lamassu-server@2.x instance.

The Bitstamp module would be a good place to start. It was updated to support the next generation server between v0.2.0 and v1.0.2: https://github.com/lamassu/lamassu-bitstamp/compare/v0.2.0...master

This is the function which the server calls upon to execute a trade: https://github.com/lamassu/lamassu-server/blob/master/lib/plugins.js#L474 You can run that in order to test the module purchases, or I can provide instructions on running the latest lamassu-machine versions in harness and pairing your server to it.

**Comment by seigneur** [comment]
@naconner  Hi Neal, I am having some issue pairing my harness to a DO lamassu-server, I user --mockPair followed by the text that I got from the admin qr code, it pairs, but when I change the price ticker it does not reflect on the harness.

Also my op : connect.multipart() will be removed in connect 3.0
visit https://github.com/senchalabs/connect/wiki/Connect-3.0 for alternatives
connect.limit() will be removed in connect 3.0
lamassu-server listening on port 3000 (https)
[2015-07-04T08:21:17.235Z] DEBUG: lamassu-server/31440 on dropme2: plugin(ticker) loaded: Itbit
[2015-07-04T08:21:17.261Z] DEBUG: lamassu-server/31440 on dropme2: plugin(transfer) loaded: Blockchain
[2015-07-04T08:21:17.267Z] DEBUG: lamassu-server/31440 on dropme2: plugin(trade) loaded: Itbit

I am assuming you got the error while doing a trade so want to replicate it.

**Comment by CrypticaScriptura** [comment]
Hi @seigneur , it's probably best to pair manually using this process (or use it to confirm the existing pairing): https://gist.github.com/naconner/dfcd1df97e9633c27ec6

In your server logs, I don't see periodic poll requests from the machine. Could you let me know what command you're using to run the lamassu-machine process?

Once paired, we should drop the --mockTrading flag and add --mockBTC, specifying an address you own.

**Comment by seigneur** [comment]
Thanks @naconner, the  --mockPair works.

By the way I have not done an RCA but whenever I do "lamassu-update-config itbit.json" the correct variables do not get updated.
Instead if I navigate to lamassu-scripts and run from the file it updates correctly.

I did a mock trade($1) and the error I got was that the amount was to small,
" ERROR: lamassu-server/31440 on dropme2: amount too small
    Error: amount too small
", will try a bigger amount later, but till now I did not get the issue that you highlighted above.

**Comment by CrypticaScriptura** [comment]
Great, @seigneur.

Does itBit have a minimum trade amount? Bitstamp does, so if trades are below $5, our Bitstamp module holds the trade in queue until it's greater than their minimum amount.

**Comment by seigneur** [comment]
No Itbit did not have an issue, the following "(data.amount < 0.004)" in common.js is the issue for that, I can remove that and make it 0.0001 which I think is the minimum on Itbit, but then I will have to update it again when btc price reaches $2/0.0001 :-) ($2 notes are the min SGD notes as of now). The queue solution is more elegant. Will look into it as a separate issue? 
Also, could you confirm whether this particular issue is still there?

**Comment by CrypticaScriptura** [comment]
Thanks for the info @seigneur. Glad to check whether an issue persists, though could you clarify which one?
