### ISSUE TITLE
Module throws 'status code 500' when used with beta API endpoint

### ISSUE THREAD

**Issue by CrypticaScriptura** [seigneur/lamassu-itbit#3]
Using the current module with lamassu-server@1.0.2, an error is thrown when attempting to place a trade using the beta-api endpoint:

```
[2015-07-08T16:44:38.355Z] DEBUG: lamassu-server/6202 on Droplet4: poll request from: [redacted]
[2015-07-08T16:44:41.505Z] DEBUG: lamassu-server/6202 on Droplet4: checking for trades
[2015-07-08T16:44:41.505Z] DEBUG: lamassu-server/6202 on Droplet4: consolidated:  {"currency":"SGD","satoshis":3366000}
[2015-07-08T16:44:41.505Z] DEBUG: lamassu-server/6202 on Droplet4: making a trade: 0.03366
[2015-07-08T16:44:42.175Z] ERROR: lamassu-server/6202 on Droplet4: ItBit.executeRequest() failed POST request to url https://beta-api.itbit.com/v1/wallets/[redacted]/orders with nonce [redacted] and data {"side":"buy","type":"limit","currency":"XBT","amount":"0.0337","price":"326.63","instrument":"XBTSGD"}. Response status code 500, response body [object Object]
    500: ItBit.executeRequest() failed POST request to url https://beta-api.itbit.com/v1/wallets/[redacted]/orders with nonce [redacted] and data {"side":"buy","type":"limit","currency":"XBT","amount":"0.0337","price":"326.63","instrument":"XBTSGD"}. Response status code 500, response body [object Object]
        at Request._callback (/usr/local/lib/node_modules/lamassu-server/node_modules/lamassu-itbit/node_modules/itbit/itbit.js:165:15)
        at Request.self.callback (/usr/local/lib/node_modules/lamassu-server/node_modules/lamassu-itbit/node_modules/itbit/node_modules/request/request.js:372:22)
        at Request.emit (events.js:98:17)
        at Request.<anonymous> (/usr/local/lib/node_modules/lamassu-server/node_modules/lamassu-itbit/node_modules/itbit/node_modules/request/request.js:1317:14)
        at Request.emit (events.js:117:20)
        at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/lamassu-server/node_modules/lamassu-itbit/node_modules/itbit/node_modules/request/request.js:1265:12)
        at IncomingMessage.emit (events.js:117:20)
        at _stream_readable.js:943:16
        at process._tickCallback (node.js:419:13)
```

Have there been changes to the beta API such that the current module is no longer compatible? 

Thanks in advance.

**Comment by seigneur** [comment]
@naconner Itbit was down on 2015-07-08  for a whole day of maintenance, this was an unplanned downtime. Just checking if you tried after that.
Thanks

**Comment by CrypticaScriptura** [comment]
@seigneur Appreciate the insight. We tried it again today and received the same error. Also double checked to ensure the API keys are correct.
